apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: N1dxbmpCRmhCaEpwSldlVVp0eGY=
  AWS_SECRET_ACCESS_KEY: ZnlrOHh6MzNFckJMZ0RXTVB1V2hVVGUwankxYTZzcFZNSDR2alVtaQ== 
  AWS_ENDPOINTS: aHR0cDovLzEzMC4xNS43LjE5Mjo5MDAw
